title: Mapping for Fun - Ginkgoch Blog

# Nav
social:
  Home: https://ginkgoch.com
  Github: https://github.com/ginkgoch
  Twitter: https://twitter.com/ginkgoch1
  Facebook: https://www.facebook.com/yun.ginkgoch.1

# Background image, color
background: '#f3f3f3'

# Favicon
favicon: https://ginkgoch.com/favicon-v2.png

# SEO
keywords: 'node.js, open source, library, shapefile, command line tool, release, electron map, map, gis software, map server, build map, docker, golang, lodash, map tutorial, map sdk, tutorial'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
